
from utils.logging_utils import setup_logger
import torch
from PIL import Image
from transformers import Blip2Processor, Blip2ForConditionalGeneration
class VLMModel:
    def __init__(self, model_path: str, device: str = None, log_file: str = "vlm_model.log"):
        self.logger = setup_logger(self.__class__.__name__, log_file)
        try:
            self.logger.info(f"Initializing VLMModel with model_path: {model_path}")
            self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
            self.logger.info(f"Using device: {self.device}")
            self.processor = Blip2Processor.from_pretrained(
                model_path,
                dtype=torch.bfloat16,
                device_map="auto",
                local_files_only=True
            )
            self.processor.image_processor.size = {"height": 224, "width": 224}
            self.processor.image_processor.do_resize = True
            self.processor.image_processor.do_center_crop = False
            self.model = Blip2ForConditionalGeneration.from_pretrained(model_path, local_files_only=True).to(self.device)
            self.model.eval()
            self.logger.info("Model and processor loaded successfully.")
            self.logger.debug(f"Device: {next(self.model.parameters()).device}")
        except Exception as e:
            self.logger.error(f"Error during VLMModel initialization: {e}", exc_info=True)
            raise
    
    def get_full_name(self, subtype):
        mapping = {
            "ALL": "Acute Lymphoblastic Leukemia(ALL)",
            "AML": "Acute Myeloid Leukemia(AML)",
            "CLL": "Chronic Lymphocytic Leukemia(CLL)",
            "CML": "Chronic Myeloid Leukemia(CML)",
            "HEALTHY": "Healthy (No Leukemia Detected)"
        }
        return mapping.get(subtype, "Unknown subtype")
    
    def predict(self, image_path: str, predicted_class: str, prompt: str, max_length: int = 128) -> str:
        try:
            
            subtypedescription = self.get_full_name(predicted_class)
            
            updatedprompt = f"This image has been classified as {subtypedescription} by the CNN model." + prompt
            
            self.logger.info(f"Running prediction on image: {image_path} with prompt: '{updatedprompt}'")
            image = Image.open(image_path).convert("RGB")
            self.logger.debug("Image loaded and converted to RGB.")
            inputs = self.processor(text=updatedprompt, return_tensors="pt").to(self.device)
            pixel_values = self.processor(images=image, return_tensors="pt").pixel_values.to(self.device)
            self.logger.debug("Inputs and pixel values prepared.")
            outputs = self.model.generate(
                input_ids=inputs.input_ids,
                pixel_values=pixel_values,
                #max_length=max_length,
                max_new_tokens=256,                
                #num_beams=5,
                #do_sample=True,
                do_sample=False,
                num_beams=1,
                repetition_penalty=1.5,
                no_repeat_ngram_size=3
                #length_penalty=1.2,
                #temperature=0.8
            )
            self.logger.debug("Output generated by model.")
            # Decode output
            generated_text = self.processor.decode(
                outputs[0],
                skip_special_tokens=True
            )
            self.logger.info(f"Generated text: {generated_text}")
            return generated_text
        except Exception as e:
            self.logger.error(f"Error during prediction: {e}", exc_info=True)
            raise
